name: test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up ROS 2
        uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: humble
          
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build ROS 2 package
        run: |
          cd ~/ros2_ws
          colcon build
          source install/setup.bash
          export PATH=$HOME/ros2_ws/install/bin:$PATH

      - name: Run test script
        run: |
          bash ~/ros2_ws/src/mypkg/test_script.sh

